version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  wkhtmltopdf-aas:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "3000:80"
